bower.json
dist/amd/index.js
dist/commonjs/index.js
dist/es6/index.js
dist/system/index.js
package.json
src/index.js

this registers the default i18n attributes if none are provided
fixes issue #13

fix(attributes): allow omitting attributes in options

---

bower.json
config.js
dist/amd/aurelia-i18n.d.ts
dist/amd/aurelia-i18n.js
dist/amd/i18n.js
dist/amd/t.js
dist/aurelia-i18n.d.ts
dist/aurelia-i18n.js
dist/commonjs/aurelia-i18n.d.ts
dist/commonjs/aurelia-i18n.js
dist/commonjs/i18n.js
dist/commonjs/t.js
dist/es6/aurelia-i18n.d.ts
dist/es6/aurelia-i18n.js
dist/es6/i18n.js
dist/es6/t.js
dist/system/aurelia-i18n.d.ts
dist/system/aurelia-i18n.js
dist/system/i18n.js
dist/system/t.js
dist/temp/aurelia-i18n.js
package.json
src/aurelia-i18n.js
src/i18n.js
src/t.js

adds the new TBindingBehavior to cowork with the TValueConverter for signaled changes. Auto signal on locale changes
fixes issue https://github.com/aurelia/i18n/issues/6

feat(signaling): provides TBindingBehavior

---

package.json

fix npm install problem

---

src/i18n.js

Prevents needing a polyfill for Symbol

fix(for-of): remove for of loop

---

config.js
package.json
src/aurelia-i18n.js

updates dependencies, adds aurelia-dependency-injection in order to fix
bundling issue
fixes issue https://github.com/aurelia/i18n/issues/72

fix(versions): update dependencies

---

README.md

doc(README): explain how to use with webpack to load submodules

---

src/defaultTranslations/relative.time.js

Signed-off-by: TheGr8Nik <andrea.niklaus@gmail.com>

feat(translation): Add italian translation

---

src/defaultTranslations/relative.time.js
src/relativeTime.js
test/unit/relative.time.spec.js

I added the italian translation.

Add italian translation

---

src/defaultTranslations/relative.time.js

feat(translation): Add portuguese translation

---

README.md

`typings install i18next --ambient` -> `typings install dt~i18next --global`

Update readme with the latest typings tool version

---

src/df.js
src/nf.js

Added binding behaviors for dates and numbers

Binding Behavior for dates and numbers

---

README.md

Fixed as per latest i18next documentation - http://i18next.com/translate/namespace/

Fix namespace and default namespace

---

src/defaultTranslations/relative.time.js

Add a locale for relative time(zh, chinese)

Add a locale(zh, chinese)

---

doc/article/en-US/i18n-with-aurelia.md

Added Webpack setup instructions.

---

doc/article/en-US/i18n-with-aurelia.md

The copied out code won't work without the import.
#206

doc(setup): TCustomAttribute should be in the import statement

---

src/aurelia-i18n-loader.js

See https://github.com/aurelia/i18n/issues/221

Feature(221): don't try to parse translation json if already parsed

---

doc/article/en-US/i18n-with-aurelia.md

doc(i18n): save npm install

---

doc/article/en-US/i18n-with-aurelia.md

Update the Browser Compatibility link to the English one instead of the Deutch one.

doc(fix) update browser compatibility link

---

doc/article/en-US/i18n-with-aurelia.md
src/i18n.js
test/unit/fixtures/template.html
test/unit/i18n.update-translations.spec.js

eg <input t="[placeholder,aria-placeholder]placeholder">
nothing too important, but something i had expected to work

allow multiple atrributes with the same key by listing them comma-seperated

---

typings.json

#290 Path in typings.json no longer targeting aurelia-i18n.d.ts

Updating typings.json to map aurelia-i18n.d.ts

---

build/build.ts

fix the d.ts file to properly import i18next dependency
closes issue https://github.com/aurelia/i18n/issues/292

fix(typings): proper import of i18next

---

build/build.ts

@zewa666 @EisenbergEffect @fkleuver

fix(build): adjust umd build for IE11 compat, add umd-es2015

---

src/defaultTranslations/relative.time.ts

This PR adds lt and pl translations for rt.
This translations where provided by our customers translation agency and should be correct, however, if anyone wants to verify the new translations, I'd be grateful :-)
A small note: I could not sign the CLA, because the link to the CLA [here](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#cla) leads to a 404.

feat(rt): translations for lt and pl

---

build/build.ts
package.json

fix the issue introduced in 3.1.2 by reverting back to default export syntax
related issue https://github.com/aurelia/i18n/issues/324

fix(dts): revert to default export

---

src/i18n.ts
src/relativeTime.ts
test/unit/i18n.spec.ts
test/unit/i18n.update-translations.spec.ts
test/unit/namespace.spec.ts
tslint.json

the TR function should not only return strings but match TResult from i18next
related issue https://github.com/aurelia/i18n/issues/331

fix(tr): result of tr
