aurelia/i18n

config.js, package.json, test/unit/i18n-attribute.spec.js
Getting two errors when running the tests though:
```
Chrome 45.0.2454 (Windows 10 0.0.0) testing i18n attributes should raise value change on i18n custom attribute FAILED
TypeError: Cannot read property 'analyze' of undefined
at Object.createModelForUnitTest (D:/Development/i18n/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:3901:48)
at Object.<anonymous> (D:/Development/i18n/test/unit/i18n-attribute.spec.js:27:48)
```
this is after changing `BehaviorInstance.createForUnitTest` to `templatingEngine.createModelForUnitTest`. I have tried to fix this by initializing aurelia-pal, but this didn't have any effect.
=> CHORE(update): update to the latest versions

src/base-i18n.js, src/t.js, test/unit/i18n.spec.js
Sorry, missed the breaking changes to the ea subscription in the PR I made yesterday. Didn't get any errors when I tested since I don't use attributes in my app.
this fixes this error:
```
ERROR [app-router] TypeError: this.subscription is not a function
at TCustomAttribute.unbind (http://10.222.201.57:8081/jspm_packages/github/aurelia/i18n@0.2.5/t.js:118:14)
at Controller.unbind (http://10.222.201.57:8081/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:2724:20)
at View.unbind (http://10.222.201.57:8081/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:841:26)
at ViewFactory.returnViewToCache (http://10.222.201.57:8081/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:1731:14)
at View.returnToCache …
```
=> fix(event-aggregator): dispose ea subscriptions correctly

src/i18n.js
Using this plugin in a TypeScript project, missing optional arguments such as `options` in `tr(key, options)` throw compiler errors since they are not marked as optional with a question mark. This PR fixes this, marking optional arguments as optional.
=> fix(i18n): marked optional arguments

src/i18n.js, test/unit/i18n-attribute.spec.js
the `text` attribute is set instead
Example which is not working without this patch:
```
<paper-input t="[label]profile:nameLabel;[error-message]profile:nameErrorMessage" value.two-way="name"></paper-input>
```
=> translation of attributes containing dash not working

dist/amd/aurelia-i18n.d.ts, dist/amd/i18n.js, dist/amd/relativeTime.js, dist/aurelia-i18n.d.ts, dist/aurelia-i18n.js, dist/commonjs/aurelia-i18n.d.ts, dist/commonjs/i18n.js, dist/commonjs/relativeTime.js, dist/es2015/aurelia-i18n.d.ts, dist/es2015/i18n.js, dist/es2015/relativeTime.js, dist/system/aurelia-i18n.d.ts, dist/system/i18n.js, dist/system/relativeTime.js, dist/temp/aurelia-i18n.js, src/i18n.js, src/relativeTime.js, test/unit/i18n.update-translations.spec.js, test/unit/relative.time.spec.js
A timeout of 10ms was introduced in [version 2.4.0 of i18next](https://github.com/i18next/i18next/blob/master/CHANGELOG.md#240). This caused two issues:
- aurelia-i18n starts to update the values before the translations are loaded. This is fixed by the first commit.
- aurelia-i18n adds translations for relative time before the translations of the users are loaded. In this situation, the XHR backend considers that the translations are already loaded and won't fetch the one defined by the users. This is fixed by the second commit.
=> Wait i18next before load

src/relativeTime.js, test/unit/relative.time.spec.js
i18n.language returns "nl-NL" on my machine, which is not defined in translations. There should probably also be better exception handling here to make clear that the language/culture is not supported.
=> Add support for culture names

README.md, doc/core-js.d.ts, doc/i18next-xhr-backend.d.ts, doc/i18next.d.ts, src/customTypings/i18next-xhr-backend.d.ts, src/customTypings/i18next.d.ts
if You try run example from documentation in typescript starterkit you will get next errors:
```
"/home/vagrant/app/src/main.ts(3,26): Cannot find module 'i18next-xhr-backend'."
"/home/vagrant/app/jspm_packages/npm/aurelia-i18n@0.5.2/aurelia-i18n.d.ts(2,23): Cannot find module 'i18next'."
```
I understand that perfect option is if authors of these libraries will provide their own implemented *.d.ts files. But could You consider adding 'temporary' d.ts files to sources of aurelia/i18n as a temporary fix?
=> complete typings for i18next and i18next-xhr-backend

README.md
It tells you to create a `locale` folder, but the loadPath uses `locales`
=> chore(readme): fix locale folder reference

package.json
Added the list of dependent modules ("aurelia-i18n/t", "aurelia-i18n/nf", "aurelia-i18n/df", "aurelia-i18n/rt") to the property aurelia/build/resources in package.json.
=> Add dependent modules to aurelia/build/resources in package.json.

README.md
It seems like when you use TypeScript and Target ES6 you do your import like in ES6, but if you target ES5 you'll need to change the import slightly (at least in TypeScript 1.8). It was not so clear by the previous comment.
=> Minor clarification regarding TypeScript imports

README.md
=> doc(README): remove reference to includeSubModules for webpack

src/i18n.js, test/unit/fixtures/template.html, test/unit/i18n.update-translations.spec.js
When the locale is change I18N#updateTranslations is triggered. This
function will call I18N#updateValue to update the translation of the
nodes. However, it will never pass the params parameters which is used
to remplate parameters in translation string by their value.
With this patch, when the value of the parameters is specified in
I18N#updateValue (for instance when it is updated in TCustomAttribute),
it is save in the I18N#params object under the translation name. The
value is then retrieved in I18N#updateValue if no parameters value is
supplied.
Note: I am not sure if my tests are good.
Close #116
=> Make sure translations parameters are always applied

src/nf.js
This update is proposed to bring it in line with the number formatter which addressed two issues (#100 & #101)
I'm not sure what the number formatter does with null or empty values but I think it makes sense to copy the behaviour from the date formatter in this case.
=> fix(nf-vc): changed signature of NfValueConverter

src/i18n.js
This will let `I18N` to be injected with required dependencies even if the plugin `configure` function is not called. This would be useful to configure the library by other means than inside bootstrapping, for example as an optional dependency in submodules.
=> feat(i18n): add dependency injection

src/relativeTime.js, test/unit/relative.time.spec.js
When using a non-default namespace, and you call the addNamespaces function it tries to load the specified namespace and also the 'translations' namespace.
This is due to the relativetime module being hard coded to the 'translations' namespace.
=> Using non-default defaultNS and adding namespaces dynamically

src/i18n.js, src/t.js, test/unit/i18n.spec.js, test/unit/i18n.update-translations.spec.js
params are reissued properly on locale change. Removal of unnecessary
Promise wrapping of updateValue.
Fixes issue
https://github.com/aurelia/i18n/issues/156
https://github.com/aurelia/i18n/issues/147
https://github.com/aurelia/i18n/issues/143
https://github.com/aurelia/i18n/issues/116
=> fix(attribute): TAttribute related fixes

doc/i18next-xhr-backend.d.ts
Currently, if you try to use the `i18next-xhr-backend.d.ts` using TypeScript 2.0, you get the following error:
<pre>
Error: typings\globals\i18next-xhr-backend\index.d.ts(24,30): error TS2314: Generic type 'Array<T>' requires 1 type
argument(s).
</pre>
The solution is to specify an type argument.
=> Fix i18next-xhr-backend.d.ts array type error

doc/article/en-US/i18n-with-aurelia.md
Spacing prevents first line of <source-code> tag from being recognized as code.
=> Fix(docs): Fix spacing in <source-code> elements

doc/article/en-US/i18n-with-aurelia.md
The current docs don't show how to add a `gulp.watch` task to the translation files. Without this task, even if the `--watch` flag was provided, the user has to manually run `au run/build` whenever he changes the translation file.
In addition, CLI is using [posix](https://nodejs.org/api/path.html#path_path_posix) internally. So, paths with `\\something\\` aren't necessary anymore. (I haven't tested on Windows though)
The source property was changed from : `"locales/**/*.json"` to `"src/locales/**/*.json"` because `gulp.watch` needs the `src` part to work. The bundle works with or without it though.
Please, tell me if something is not right then I will edit the PR.
Thanks!
=> doc(using-aurelia-cli): add gulp.watch instructions

doc/article/en-US/i18n-with-aurelia.md
Added missing call to getRelativeTime in the example.
Couple of minor corrections to the text around it.
=> Correct RelativeTime example in i18n documentation

src/t.js
Related: https://github.com/aurelia/templating/pull/535
Resolves: https://github.com/aurelia/i18n/issues/192
Allow configuration of aliases (which exist on the metadata) on both
the `t-params` and `t` attributes.
Dependent on https://github.com/aurelia/templating/pull/535 being merged in first to enable alias support
=> fix(t): expose configuration of aliases

doc/article/en-US/i18n-with-aurelia.md
Changed the help to correctly explain how to successfully register aliases for the "t" attribute.
fixes #206
=> Corrected help about registering aliases for [t]

doc/article/en-US/i18n-with-aurelia.md
Changed the docs to add a quick example showing how to include `.json` files in the Aurelia bundle by including them in the text extension
When i first added `aurelia-i18n` to my project, i missed this section and for "new-starters" this may help explicitly call it out
=> Added example for including ".json" as text

src/i18n.js, test/unit/numberformat.spec.js
Undocumented uf() should remove all commas when it parses a string such as "1,234,567".
Currently it removes only the first ',' and causes an error.
=> fix(uf()): remove all thousand seperators

doc/article/en-US/i18n-with-aurelia.md
Documentation does not describe how to reference strings in non-defaultNS files.
=> Accessing strings in non-default namespace files

doc/article/en-US/i18n-with-aurelia.md
explain what the custom attributes option is used for, what the defaults are and why there
is a need to register them in two places.
Fixes issue https://github.com/aurelia/i18n/issues/222
=> docs(options): explain attributes option

src/defaultTranslations/relative.time.js
locale for Japanese is ja, not jp. relativeTime does not work for Japanese language due to this error.
I added ja with remaining jp for compatibility.
=> locale for Japanese is ja, not jp in relative.time.js

doc/article/en-US/i18n-with-aurelia.md
My VSCode is set to `files.trimTrailingWhitespace` and so it also seems to have trim a few white spaces here and there. I think it's still acceptable
=> doc (i18n): fix #247 add clarity to t-params via code

doc/article/en-US/i18n-with-aurelia.md
Typings tool has been deprecated in favour or NPM or Yarn. Mention of using
the typings tool is removed and the recommenced way of using NPM or
alternatively the other popular too Yarn.
=> Removes deprecated notes about typings

doc/article/en-US/i18n-with-aurelia.md
It appears Aurelia cannot load "aurelia-i18n" plugin (in all configurations)
without using the PLATFORM.modulename utility. This was the case with WebPack
at least. This also adds an example configuration in TypeScript.
=> Adds PLATFORM.modulename to internationalization module loading

karma.conf.js, package.json, src/i18n.js, src/relativeTime.js, test/unit/relative.time.spec.js
stops forcing the lng option in favor of relativetime and uses the fallbackLng instead
Related issue https://github.com/aurelia/i18n/issues/254
=> fix(i18n): stop forcing lng option

doc/article/en-US/i18n-with-aurelia.md
There was an extra brace `});` at the bottom. It probably wasn't noticed because of the extra indentation.
=> doc(i18n-with-aurelia): remove unnecessary brace and fix indentation

doc/article/en-US/i18n-with-aurelia.md
For the love of god, i couldn't get any of the instructions to use aurelia-i18n with webpack and i18n-xhr-backend/aurelia-loader to work. Nothing from here or the web worked for we. 
In contrast, using [i18next-resource-store-loader](https://github.com/atroo/i18next-resource-store-loader) was very simple and worked. Hence i propose to add to the docs the apparently much simpler alternative of using `resources` and i18next-resource-store-loader instead of `backend` and i18n-xhr-backend/aurelia-loader. Bundled translations are not a backend anyways.
=> doc(webpack): instructions to bundle translations with webpack

doc/article/en-US/i18n-with-aurelia.md
I finally got webpack to work with unbundled translations and wanted to share it, particularly since it was easy in the end.  The position of this addition isn't optimal, but neither do i see a better place. 
I still have no idea how to get webpack and Backend.with(aurelia.loader) to work, but with one easy unbundled option (this one) and an easy bundled option (last commit), i certainly not gonna try further.
=> doc(webpack): Using i18next-xhr-backend with webpack

doc/article/en-US/i18n-with-aurelia.md
The section about using `BaseI18N` was outdated:
* `TCustomAttribute` already observes language change events and updates itself.
* Base18N does not respect `t-params`, causing incorrect translations.
See #273 for details.
=> Update I18N documentation

doc/article/en-US/i18n-with-aurelia.md
In the documentation to Bundle Translation Files with the cli, the watch task must be added to the new watch.ts file, and not in run.ts, since one of the last aurelia-cli update.
See #285 for details.
=> fix(doc): fix bundle translation files doc for new CLI watch task

typings.json
npm typings install step was broken because this is missing
Started get build failures stating 
https://raw.githubusercontent.com/aurelia/i18n/master/typings.json responded with 404, expected it to equal 200
=> Re-add typings.json

build/build.ts, package.json
@zewa666 From typings file, I assume namespace of i18next is `i18next`, please change if needed in `build.ts`
cc @EisenbergEffect
=> refactor(build): add umd build target, cdn fields

build/build.ts
Use the `import * as i18next from 'i18next'` syntax in the generated .d.ts file. This PR replaces https://github.com/aurelia/i18n/pull/297.
=> chore(build) use "import * as i18next" in generated .d.ts file

package.json
@EisenbergEffect @zewa666 this is to help avoid bloating aurelia-script users, when they use umd module format from this module
=> fix(dist): adjust unpkg field

package-lock.json, src/i18n.ts, test/unit/t-attribute.spec.ts
if the provided value is bound to a null or undefined property
the resulting value for translation should be an empty string
fixes issue https://github.com/aurelia/i18n/issues/313
=> fix(t-attribute): undefined and null bound values

build/build.ts, package-lock.json, package.json
Fixes #324
* Removed @types/i18next devDependency (deprecated)
* Updated i18next dependency from 14.0.1 to 14.1.1 - now with typings includes.
* Removed the typings fix part of the build script - should no longer be needed when using the typings from the i18next package (default import statement in aurelia-18n typings is now correct since i18next typings has default export. No special tsconfig settings should be required anymore).
=> Removed i18next default import typings fix
